# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy project files
COPY . .

# Build the project
RUN npm run build

# Expose any necessary port if needed (Not needed for stdio based MCP servers)

# Command to start the MCP server
CMD [ "node", "build/index.js" ]
